"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Eye, EyeOff, Mail, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { OtpInput } from "@/components/otp-input";

type Mode = "login" | "register" | "forgot";
async function action(body: Record<string, unknown>) { const response = await fetch("/api/platform", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw Error(result.error); return result; }
export function AuthForm({ mode }: { mode: Mode }) {
  const [step, setStep] = useState<"form" | "otp">("form");
  const [method, setMethod] = useState<"password" | "code">("password");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [role, setRole] = useState<"buyer" | "seller">("seller");
  const [code, setCode] = useState("");
  const [show, setShow] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [countdown, setCountdown] = useState(0);
  useEffect(() => { if (!countdown) return; const timer = window.setInterval(() => setCountdown(value => Math.max(0, value - 1)), 1000); return () => clearInterval(timer); }, [countdown]);
  async function sendCode() { setBusy(true); setError(""); try { await action({ action: "otp", email }); setStep("otp"); setCountdown(60); } catch (e) { setError(e instanceof Error ? e.message : "Envoi impossible"); } finally { setBusy(false); } }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { if (step === "form") { if (mode === "login" && method === "password") { await action({ action: "login", email, password }); location.href = "/vendeur"; return; } await action({ action: "otp", email }); setStep("otp"); setCountdown(60); } else { if (code.length !== 6) throw Error("Saisissez les six chiffres du code."); if (mode === "register") await action({ action: "verifyRegister", email, password, code, role }); else if (mode === "forgot") await action({ action: "resetPassword", email, password, code }); else await action({ action: "verifyLogin", email, code }); location.href = mode === "register" && role === "seller" ? "/vendeur/demarrage" : mode === "login" ? "/vendeur" : "/"; } } catch (e) { setError(e instanceof Error ? e.message : "Action impossible"); } finally { setBusy(false); } }
  return <form className="auth-form" onSubmit={submit} noValidate>{mode === "login" && step === "form" && <div className="auth-method"><button type="button" className={method === "password" ? "active" : ""} onClick={() => setMethod("password")}>Mot de passe</button><button type="button" className={method === "code" ? "active" : ""} onClick={() => setMethod("code")}>Code par e-mail</button></div>}{mode === "register" && step === "form" && <div className="role-choice"><button type="button" className={role === "seller" ? "active" : ""} onClick={() => setRole("seller")}><strong>Je vends</strong><span>Créer une boutique professionnelle</span></button><button type="button" className={role === "buyer" ? "active" : ""} onClick={() => setRole("buyer")}><strong>J’achète</strong><span>Suivre mes commandes</span></button></div>}{step === "form" ? <><label><span>Adresse e-mail</span><div className="input-icon"><Mail /><input type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="email" placeholder="vous@exemple.com" required /></div></label>{(method === "password" || mode !== "login") && <label><span>{mode === "forgot" ? "Nouveau mot de passe" : "Mot de passe"}</span><div className="input-icon"><input type={show ? "text" : "password"} value={password} onChange={e => setPassword(e.target.value)} minLength={10} maxLength={128} autoComplete={mode === "login" ? "current-password" : "new-password"} required /><button type="button" aria-label={show ? "Masquer" : "Afficher"} onClick={() => setShow(!show)}>{show ? <EyeOff /> : <Eye />}</button></div>{mode !== "login" && <small className={password.length >= 10 ? "valid" : ""}>Au moins 10 caractères</small>}</label>}{mode === "login" && method === "password" && <Link href="/mot-de-passe-oublie" className="forgot-link">Mot de passe oublié ?</Link>}<Button disabled={busy}>{busy ? "Veuillez patienter…" : mode === "login" && method === "password" ? "Se connecter" : "Recevoir mon code"}</Button></> : <><div className="otp-copy"><span>Code envoyé</span><h2>Vérifiez votre boîte de réception</h2><p>Entrez le code envoyé à <strong>{email}</strong>. Il expire dans 10 minutes.</p></div><OtpInput value={code} onChange={setCode} />{error && <p className="field-error">{error}</p>}<Button disabled={busy || code.length !== 6}>{busy ? "Vérification…" : mode === "forgot" ? "Modifier mon mot de passe" : "Vérifier et continuer"}</Button><div className="otp-actions"><button type="button" onClick={() => { setStep("form"); setCode(""); }}>Modifier l’e-mail</button><button type="button" disabled={countdown > 0 || busy} onClick={sendCode}><RefreshCw />{countdown ? `Renvoyer dans ${countdown}s` : "Renvoyer le code"}</button></div></>}{error && step === "form" && <p className="field-error">{error}</p>}<div className="auth-bottom">{mode === "login" ? <>Pas encore de compte ? <Link href="/inscription">Créer un compte</Link></> : <>Déjà inscrit ? <Link href="/connexion">Se connecter</Link></>}</div></form>;
}
