"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, Scissors, Sparkles, Tags } from "lucide-react";
import { Button } from "@/components/ui/button";

export function ServicesPage() {
  const [user, setUser] = useState(false), [requests, setRequests] = useState<Record<string, string>[]>([]), [done, setDone] = useState(false), [error, setError] = useState("");
  useEffect(() => { fetch("/api/me", { cache: "no-store" }).then(r => r.json()).then(data => { setUser(Boolean(data.user)); setRequests(data.requests || []); }); }, []);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); const form = event.currentTarget; const response = await fetch("/api/platform", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "request", ...Object.fromEntries(new FormData(form)) }) }); const result = await response.json(); if (!response.ok) { setError(result.error); return; } setDone(true); form.reset(); }
  const services = [{ title: "Liquidation", icon: Tags, copy: "Écouler un stock dormant auprès d’une communauté engagée.", steps: ["Diagnostic du stock", "Mise en ligne", "Pilotage des ventes"] }, { title: "Upcycling", icon: Scissors, copy: "Transformer l’existant avec des ateliers partenaires tunisiens.", steps: ["Sélection des pièces", "Proposition créative", "Nouvelle collection"] }, { title: "Redesign", icon: Sparkles, copy: "Repenser une gamme pour lui redonner valeur et désirabilité.", steps: ["Brief de marque", "Direction créative", "Accompagnement lancement"] }];
  return <><div className="sf-page-head"><span>Accompagnement professionnel</span><h1>Votre stock mérite une nouvelle stratégie.</h1><p>De l’analyse à la remise sur le marché, l’équipe Stocky construit le parcours adapté.</p></div><div className="service-cards">{services.map(({ title, icon: Icon, copy, steps }) => <article key={title}><Icon /><h2>{title}</h2><p>{copy}</p><ol>{steps.map((step, index) => <li key={step}><i>{index + 1}</i>{step}</li>)}</ol></article>)}</div><section className="service-request"><div><span>Parlons de votre stock</span><h2>Recevoir une recommandation personnalisée</h2><p>Décrivez votre volume, le type de pièces et votre objectif. Nous vous répondons directement dans votre espace.</p></div>{user ? <form onSubmit={submit}><label><span>Service souhaité</span><select name="type"><option>Liquidation</option><option>Upcycling</option><option>Redesign</option><option>Support</option></select></label><label><span>Votre besoin</span><textarea name="message" minLength={10} required placeholder="Type de stock, volume, état, objectif…" /></label>{error && <p className="field-error">{error}</p>}{done && <p className="success-message"><CheckCircle2 /> Votre demande est enregistrée.</p>}<Button>Envoyer ma demande <ArrowRight /></Button></form> : <div className="login-required"><p>Connectez-vous à votre espace boutique pour envoyer et suivre une demande.</p><Button asChild><Link href="/connexion">Se connecter</Link></Button></div>}</section>{requests.length > 0 && <section className="my-requests"><h2>Mes demandes</h2>{requests.map(r => <article key={r.id}><div><strong>{r.type}</strong><span className={`status-badge ${r.status}`}>{r.status === "new" ? "Nouvelle" : r.status === "processing" ? "En cours" : "Résolue"}</span></div><p>{r.message}</p>{r.reply && <blockquote>{r.reply}</blockquote>}</article>)}</section>}</>;
}
