import assert from 'node:assert/strict';
const base='http://127.0.0.1:3001';
const makeClient=()=>{let cookie='';return async(body)=>{const r=await fetch(base+'/api/platform',{method:body?'POST':'GET',headers:{origin:base,'content-type':'application/json',cookie},body:body?JSON.stringify(body):undefined});if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,data:await r.json()}}};
const admin=makeClient(),seller=makeClient(),other=makeClient(),guest=makeClient();
assert.equal((await guest({action:'deleteDemo'})).status,401);
assert.equal((await admin({action:'pin',pin:process.env.TEST_ADMIN_PIN})).status,200);
const suffix=Date.now();
assert.equal((await seller({action:'register',email:`seller-${suffix}@example.test`,password:'Test-Strong-Password-2026'})).status,200);
assert.equal((await other({action:'register',email:`other-${suffix}@example.test`,password:'Test-Strong-Password-2026'})).status,200);
assert.equal((await seller({action:'store',name:'Integration Store',phone:'00000000'})).status,200);
let info=(await seller()).data;const store=info.stores.find(s=>s.owner===info.user.id);
assert.equal(store.status,'pending');
assert.equal((await seller({action:'moderate',entity:'store',id:store.id,status:'active'})).status,403);
assert.equal((await admin({action:'moderate',entity:'store',id:store.id,status:'active'})).status,200);
assert.equal((await seller({action:'product',name:'Integration Product',price:29.5,stock:2,category:'Mode',description:'Test'})).status,200);
info=(await seller()).data;const product=info.products.find(p=>p.store_id===store.id);
assert.equal((await guest()).data.products.some(p=>p.id===product.id),false);
assert.equal((await admin({action:'moderate',entity:'product',id:product.id,status:'active'})).status,200);
assert.equal((await other({action:'inventory',id:product.id,stock:999})).status,403);
const checkout={action:'checkout',items:[{id:product.id,quantity:2}],customer:'Integration Test',phone:'00000000',address:'Test-only address'};
const bought=await guest(checkout);assert.equal(bought.status,200);
assert.equal((await guest(checkout)).status,400);
info=(await seller()).data;const order=info.orders.find(o=>o.id===bought.data.orders[0]);
assert.equal(order.total,59000);
assert.equal(info.products.find(p=>p.id===product.id).stock,0);
assert.equal((await other()).data.orders.length,0);
assert.equal((await other({action:'orderStatus',id:order.id,status:'cancelled'})).status,403);
assert.equal((await seller({action:'orderStatus',id:order.id,status:'cancelled'})).status,200);
assert.equal((await seller()).data.products.find(p=>p.id===product.id).stock,2);
assert.equal((await seller({action:'orderStatus',id:order.id,status:'cancelled'})).status,400);
console.log('PASS: real sessions, private administration, seller ownership, moderation, checkout, stock, cancellation and order isolation.');
